apiVersion: apps/v1
kind: Deployment
metadata:
  name: apuestas
  namespace: casino
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: apuestas
  template:
    metadata:
      labels:
        app: apuestas
    spec:
      containers:
        - name: apuestas
          image: 851725353324.dkr.ecr.us-east-1.amazonaws.com/casino/apuestas-service:latest
          ports:
            - containerPort: 8000
          env: